### ISSUE TITLE
Potential security breach.

### ISSUE THREAD

**Issue by agood-boy** [naokikimura/chrome-web-store-api#6]
Potential security breach. Google OAuth Key in Url in file [/README.md](https://github.com/naokikimura/chrome-web-store-api/tree/master/README.md)

You should recycle your credenttials immediately and move secrets to environment variables to prevent them being committed to GitHub.

Hope this will be helpful to you！

shout me a coffee ☕️ via [PayPal](https://www.paypal.me/agoodboy)

<a href="https://www.paypal.me/agoodboy">
  <img width="160" height="41" src="https://raw.githubusercontent.com/DWilliames/paddy-sketch-plugin/master/.images/paypal-badge.png" >
</a>

**Comment by naokikimura** [comment]
There is no problem because credentials are fake.
